name: Branch Name Check

on:
  pull_request:
    branches: ['main', 'dev', 'feature/*', 'fix/*', 'test/*']

  workflow_dispatch:

jobs:
  branch-name-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch
        run: echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Verify branch name
        run: |
          branch_name="${{ steps.branch.outputs.branch_name }}"
          if [[ "$branch_name" == "dev" || "$branch_name" == "main" || "$branch_name" =~ .*patch.* ]]; then
            echo "Ignoring branch: $branch_name"
          elif [[ ! "$branch_name" =~ ^(feature|test|fix|hotfix)\/.* ]]; then
            echo "Branch name should start with 'feature', 'test', 'fix', or 'hotfix'."
            exit 1
          fi
